# Generated by Django 2.2.7 on 2019-11-13 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('s', 'Student'), ('p', 'Professor'), ('t', 'Teaching Assistant')], default='s', max_length=1)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lab')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('timeSubmitted', models.DateTimeField()),
                ('timeCompleted', models.DateTimeField(blank=True)),
                ('feedback', models.IntegerField(blank=True)),
                ('huid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huid', to=settings.AUTH_USER_MODEL)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lab')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
