# Generated by Django 2.2.7 on 2019-11-14 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='feedback',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='huid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='timeCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
