# Generated by Django 2.2.7 on 2019-11-15 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191114_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCode',
            fields=[
                ('code', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('s', 'Student'), ('p', 'Professor'), ('t', 'Teaching Assistant')], default='s', max_length=1)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lab')),
            ],
        ),
    ]
