# Generated by Django 2.2.7 on 2019-11-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191114_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcode',
            name='code',
            field=models.CharField(default='<function', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
