# Generated by Django 2.2.7 on 2019-11-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191114_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcode',
            name='code',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
