# Generated by Django 2.2.7 on 2020-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lab_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lastSub',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='initialSub',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subRenewal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
