# Generated by Django 2.2.7 on 2020-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200213_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='orderID',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
