# Generated by Django 2.2.7 on 2020-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_subscription_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
