# Generated by Django 2.2.7 on 2020-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_request_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='taViewFeedback',
            field=models.BooleanField(default=True),
        ),
    ]
