# Generated by Django 2.2.7 on 2020-03-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_lab_taviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
